### ISSUE TITLE
Screenshots in Readme still have PX Blue text

### ISSUE THREAD

**Issue by surajeaton** [etn-ccis/blui-react-native-cli-templates#74]
#### Describe the bug / expected behavior
Screenshots in README.md still has **PX Blue** instead of **Brighlayer UI**

#### What are the steps to reproduce?
1. Go to... https://github.com/etn-ccis/blui-react-native-cli-templates
2. Scroll down to Readme
3. See the attached screenshots have **PX Blue**

#### Screenshots / Screen recording
<img width="459" alt="Screenshot 2023-01-11 at 2 13 35 PM" src="https://user-images.githubusercontent.com/120575281/211759171-798f2562-ec32-4b43-a1c5-6e00b146ef64.png">
<img width="483" alt="Screenshot 2023-01-11 at 2 14 09 PM" src="https://user-images.githubusercontent.com/120575281/211759322-fb373128-198a-472d-9dc8-48b69feaa775.png">
<img width="491" alt="Screenshot 2023-01-11 at 2 14 50 PM" src="https://user-images.githubusercontent.com/120575281/211759456-4f6316b8-03cb-4895-b429-854e98cccecc.png">

#### Code snippet / Link to minimum reproduction example

```
CODE HERE
```

#### Suggested fix
Update the screenshots

**Comment by daileytj** [comment]
If the new screens arent generic already, update them locally to be generic and screenshot those to ensure we don't run into this problem again if there is another UI shift or rebrand.
